/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of applications that will be loaded inside the frame
 *
 * @minItems 1
 */
export type Applications = [
  {
    id: string;
    label: string;
    icon: string;
    url: string;
    manifest: string;
    [k: string]: unknown;
  },
  ...{
    id: string;
    label: string;
    icon: string;
    url: string;
    manifest: string;
    [k: string]: unknown;
  }[]
];
